// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cmdb.Models;

namespace cmdb.Migrations
{
    [DbContext(typeof(CmdbContext))]
    [Migration("20210814090214_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("cmdb.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory");

                    b
                        .UseCollation("utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("cmdb.Models.Permission", b =>
                {
                    b.Property<long>("PermisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PermissionDes")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("權限描述");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("PermisionId")
                        .HasName("PRIMARY");

                    b.ToTable("permission");

                    b
                        .HasComment("權限列表")
                        .UseCollation("utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("cmdb.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasComment("新增使用者");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("新增時間");

                    b.Property<long?>("DeleteBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("修改時間");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleId" }, "Id_UNIQUE")
                        .IsUnique();

                    b.ToTable("roles");

                    b
                        .HasComment("角色定義")
                        .UseCollation("utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("cmdb.Models.RolePermission", b =>
                {
                    b.Property<string>("RolePermissionId")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("isActive")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PermisionId")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.ToTable("role_permission");

                    b
                        .HasComment("角色權限")
                        .UseCollation("utf8mb4_0900_ai_ci");
                });

            modelBuilder.Entity("cmdb.Models.User", b =>
                {
                    b.Property<long>("CreateBy")
                        .HasColumnType("bigint")
                        .HasComment("新增使用者");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("新增時間");

                    b.Property<long?>("DeleteBy")
                        .HasColumnType("bigint")
                        .HasComment("刪除使用者");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("聯絡信箱");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'")
                        .HasComment("已啟用");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)")
                        .HasComment("已刪除");

                    b.Property<bool>("IsVarify")
                        .HasColumnType("tinyint(1)")
                        .HasComment("已驗證");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasComment("連絡電話");

                    b.Property<DateTime>("ModifyTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("修改時間");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("'0000'")
                        .HasComment("密碼");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasComment("使用者角色");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("使用者ID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("使用者名稱");

                    b.HasIndex(new[] { "UserId" }, "Id_UNIQUE")
                        .IsUnique();

                    b.ToTable("users");

                    b
                        .HasComment("使用者")
                        .UseCollation("utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("cmdb.Models.UserPermission", b =>
                {
                    b.Property<string>("UserPermissionId")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("IsActive")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("isActive");

                    b.Property<string>("PermisionId")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPermissionId");

                    b.ToTable("user_permission");

                    b
                        .HasComment("使用者權限")
                        .UseCollation("utf8mb4_0900_ai_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
